error: absolute paths must start with `self`, `super`, `crate`, or an external crate name in the 2018 edition
  --> $DIR/edition-lint-fully-qualified-paths.rs:18:25
   |
LL |     let _: <foo::Baz as ::foo::Foo>::Bar = ();
   |                         ^^^^^^^^^^
   |
   = warning: this is accepted in the current edition (Rust 2015) but is a hard error in Rust 2018!
   = note: for more information, see issue #53130 <https://github.com/rust-lang/rust/issues/53130>
note: the lint level is defined here
  --> $DIR/edition-lint-fully-qualified-paths.rs:3:9
   |
LL | #![deny(absolute_paths_not_starting_with_crate)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: use `crate`
   |
LL |     let _: <foo::Baz as crate::foo::Foo>::Bar = ();
   |                         ~~~~~~~~~~~~~~~

error: absolute paths must start with `self`, `super`, `crate`, or an external crate name in the 2018 edition
  --> $DIR/edition-lint-fully-qualified-paths.rs:18:25
   |
LL |     let _: <foo::Baz as ::foo::Foo>::Bar = ();
   |                         ^^^^^^^^^^
   |
   = warning: this is accepted in the current edition (Rust 2015) but is a hard error in Rust 2018!
   = note: for more information, see issue #53130 <https://github.com/rust-lang/rust/issues/53130>
   = note: duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`
help: use `crate`
   |
LL |     let _: <foo::Baz as crate::foo::Foo>::Bar = ();
   |                         ~~~~~~~~~~~~~~~

error: absolute paths must start with `self`, `super`, `crate`, or an external crate name in the 2018 edition
  --> $DIR/edition-lint-fully-qualified-paths.rs:24:13
   |
LL |     let _: <::foo::Baz as foo::Foo>::Bar = ();
   |             ^^^^^^^^^^
   |
   = warning: this is accepted in the current edition (Rust 2015) but is a hard error in Rust 2018!
   = note: for more information, see issue #53130 <https://github.com/rust-lang/rust/issues/53130>
help: use `crate`
   |
LL |     let _: <crate::foo::Baz as foo::Foo>::Bar = ();
   |             ~~~~~~~~~~~~~~~

error: aborting due to 3 previous errors

