use std::io::Error;

fn main() -> Result<(), Box<Error>> {
    Ok(())
}
